// ============================================================
// PROJECTS DATA
// Add/remove/edit projects here — the UI in projects.js renders
// automatically from this array. Nothing else needs to change.
// ============================================================
const projectsLibrary = [
    { id: 1, name: "Ola Data Analysis Project", shortDesc: "In-depth analysis of Ola ride data: operational KPIs, ride trends, driver performance using Power BI & SQL.", techStack: ["Power BI", "SQL"], category: "analytics", githubLink: "https://github.com/Karankukadiya/Ola-DashBoard", outcome: "Dashboard revealing peak hours, revenue leakage points, and driver efficiency scores.", icon: "fa-car" },
    { id: 2, name: "Credit Card Financial Dashboard", shortDesc: "Executive dashboard tracking revenue, transaction behavior, customer segmentation, interest earnings with DAX metrics.", techStack: ["Power BI", "SQL", "DAX"], category: "analytics", githubLink: "https://github.com/Karankukadiya/Credit-Card-Financial-Dashboard", outcome: "Actionable insights on acquisition costs & customer profitability.", icon: "fa-credit-card" },
    { id: 3, name: "Customer Behaviour Analysis", shortDesc: "RFM segmentation, purchasing patterns, product affinity using Python, Power BI & SQL.", techStack: ["Power BI", "SQL", "Python"], category: "analytics", githubLink: "https://github.com/Karankukadiya/Customer-Behavior-Analysis", outcome: "Identified high-value segments improving retention accuracy.", icon: "fa-users" },
    { id: 4, name: "Ecommerce Dashboard", shortDesc: "Interactive Power BI dashboard with DAX queries to analyze revenue, profit trends, and category performance.", techStack: ["Power BI", "DAX queries"], category: "analytics", githubLink: "https://github.com/Karankukadiya/ECOMMERCE-SALES-DASHBOARD", outcome: "Real-time monitoring of sales KPIs and product-wise profitability.", icon: "fa-shopping-cart" },
    { id: 5, name: "HR Analytics Project", shortDesc: "HR metrics dashboard: attrition, employee performance, retention drivers & workforce demographics.", techStack: ["Power BI", "DAX queries"], category: "analytics", githubLink: "https://github.com/Karankukadiya/HR-Analytics-Dashboard", outcome: "Reduced attrition by highlighting key drivers and improving talent strategies.", icon: "fa-chart-pie" },
    { id: 6, name: "Customer Churn Prediction", shortDesc: "ML model to predict churn + Streamlit web app. Integrated Power BI visualization.", techStack: ["Power BI", "Python", "ML", "Streamlit"], category: "ml", githubLink: "https://github.com/Karankukadiya/Customer-Churn-Prediction", outcome: "Predictive tool achieving 86% recall, deployed web app for business teams.", icon: "fa-chart-line" },
    { id: 7, name: "House Price Prediction", shortDesc: "Regression model for housing prices with feature engineering and Streamlit frontend.", techStack: ["Python", "ML", "Streamlit"], category: "ml", githubLink: "https://github.com/Karankukadiya/House-Price-Prediction", outcome: "Accurate pricing estimates with interactive UI for real estate analysts.", icon: "fa-home" },
    { id: 8, name: "Sales Analysis EDA", shortDesc: "Exploratory data analysis on sales data using Python (Pandas, Matplotlib, Seaborn).", techStack: ["Python"], category: "engineering", githubLink: "https://github.com/Karankukadiya/sales_analysis_eda", outcome: "Data-driven recommendations for inventory & promotional planning.", icon: "fa-chart-bar" },
    { id: 9, name: "Data Wrangling & ETL Pipeline (Alteryx Inspired)", shortDesc: "Python-based ETL pipeline with data cleaning, transformation automation.", techStack: ["Python"], category: "engineering", githubLink: "https://github.com/Karankukadiya/Data-Wrangling-ETL-Pipeline-Alteryx-Inspired-", outcome: "Reduced manual data prep time using reusable pipeline modules.", icon: "fa-code-branch" },
    { id: 10, name: "AI-Powered E-commerce Analytics Automation (n8n)", shortDesc: "No-code automation workflow with n8n for e-commerce data ingestion & AI reporting.", techStack: ["n8n automation"], category: "engineering", githubLink: "https://github.com/Karankukadiya/AI-Powered-E-Commerce-Analysis-Automation", outcome: "Fully automated daily reporting pipeline with AI enrichment.", icon: "fa-robot" },
    { id: 11, name: "Sales Data Analysis Dashboard (Excel)", shortDesc: "Interactive Excel dashboard analyzing sales trends, customer segments, and regional performance.", techStack: ["Microsoft Excel", "Pivot Tables", "Pivot Charts", "Power Query", "Dashboard Design", "Data Cleaning", "Data Visualization", "Business Analysis"], category: "analytics", githubLink: "https://github.com/Karankukadiya/Sales-Data-Analysis-Dashboard-Excel-", outcome: "Delivered actionable insights for sales optimization and business decisions.", icon: "fa-chart-pie" },
    { id: 12, name: "SmartSpec Analytics", shortDesc: "End-to-end smartphone market analysis using web scraping, SQL, Python, machine learning, and Power BI.", techStack: ["Python", "SQL", "PostgresSQL", "Statistical Analysis", "Predictive Modelling", "Power BI"], category: "analytics", githubLink: "https://github.com/Karankukadiya/SmartSpec-Analytics", outcome: "Delivered pricing analysis, market insights, and interactive business dashboards.", icon: "fa-mobile-screen-button" }
];
